r2013-02-12-planetspractice/config/routes.rb
R20130212Planetspractice::Application.routes.draw do
get '/planets' => 'planets#index'
get '/planets/new' => 'planets#new'
post '/planets' => 'planets#create'
get '/planets/:id' => 'planets#show', :as => 'planet'
post '/planets/:id/delete' => 'planets#destroy', :as => 'planet_delete'
root :to => 'planets#index'
get '/planets/:id/edit' => 'planets#edit', :as => 'planet_edit'
post 'planets/:id' => 'planets#update'
end

r2013-02-12-planetspractice/app/models/planet.rb
# == Schema Information
#
# Table name: planets
#
#  id    :integer          not null, primary key
#  name  :string(255)
#  image :text
#  orbit :float
#  mass  :float
#  moons :integer
#

class Planet < ActiveRecord::Base
  attr_accessible :name, :image, :orbit, :diameter, :mass, :moons
end

r2013-02-12-planetspractice/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

r2013-02-12-planetspractice/app/controllers/planets_controller.rb
class PlanetsController < ApplicationController
  def index
    @planets = Planet.all
  end

  def new
  end

  def create
    Planet.create(params[:planet])
    redirect_to(planets_path)
  end

  def show
      @planet = Planet.find(params[:id])
  end

  def destroy
    planet = Planet.find(params[:id])
    planet.delete
    redirect_to(planets_path)
  end

  def edit
    @planet = Planet.find(params[:id])
  end

  def update
    planet = Planet.find(params[:id])
    planet.update_attributes(params[:planet])
    redirect_to(planets_path)
  end
end

r2013-02-12-planetspractice/app/helpers/application_helper.rb
module ApplicationHelper
end

r2013-02-12-planetspractice/app/views/planets/edit.html.erb
<form method='post' action'<%= planet_path(@planet.id) %>'>
<br>Name: <br><input value='<%= @planet.name %>' type='text' name='planet[name]' autofocus><br>
<br>Image: <br><input value='<%= @planet.image %>' type='text' name='planet[image]'><br>
<br>Orbit: <br><input value='<%= @planet.orbit %>' type='text' name='planet[orbit]'><br>
<br>Diameter: <br><input value='<%= @planet.diameter %>' type='text' name='planet[diameter]'><br>
<br>Mass: <br><input value='<%= @planet.mass %>' type='text' name='planet[mass]'><br>
<br>Moons: <br><input value='<%= @planet.moons %>' type='text' name='planet[moons]'><br><br><br>
<button>planet me!</button>



</form>

r2013-02-12-planetspractice/app/views/planets/index.html.erb
<% @planets.each do |planet| %>
 <%= link_to(planet.name, planet_path(planet.id)) %> has <%= pluralize(planet.moons, 'moon') %>.
  <br>
  <%= button_to('Delete Planet', planet_delete_path(planet.id)) %>
  <%= link_to('Edit Planet', planet_edit_path(planet.id)) %>
<% end %>

r2013-02-12-planetspractice/app/views/planets/new.html.erb
<form metho='post' action="/planets">
<br>Name: <br><input type='text' name='planet[name]' autofocus><br>
<br>Image: <br><input type='text' name='planet[image]'><br>
<br>Orbit: <br><input type='text' name='planet[orbit]'><br>
<br>Diameter: <br><input type='text' name='planet[diameter]'><br>
<br>Mass: <br><input type='text' name='planet[mass]'><br>
<br>Moons: <br><input type='text' name='planet[moons]'><br><br><br>
<button>planet me!</button>
</form>

r2013-02-12-planetspractice/app/views/planets/show.html.erb
this is the show phile.

<%= image_tag(@planet.image) %>