r2013-02-13-moma-rails/config/routes.rb
R20130213MomaRails::Application.routes.draw do
  resources :artists, :paintings
end

r2013-02-13-moma-rails/app/models/artist.rb
# == Schema Information
#
# Table name: artists
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  nationality :string(255)
#  dob         :date
#  image       :text
#  period      :string(255)
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Artist < ActiveRecord::Base
  attr_accessible :name, :nationality, :dob, :period, :image
  has_many :paintings
end

r2013-02-13-moma-rails/app/models/painting.rb
# == Schema Information
#
# Table name: paintings
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  style      :string(255)
#  year       :float
#  image      :text
#  period     :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  artist_id  :integer
#

class Painting < ActiveRecord::Base
  attr_accessible :title, :year, :size, :style, :image, :artist_id
  belongs_to :artist
end

r2013-02-13-moma-rails/app/controllers/ artists_controller.rb
class ArtistsController < ApplicationController
  def index
    @artists = Artist.all
  end
  def create
    artist = Artist.create(params[:artist]) #artist is key to hash
    redirect_to(artist)
  end
  def new
    @artist = Artist.new
  end
  def edit
    @artist = Artist.find(params[:id])
    render 'new'
  end
  def show
    @artist = Artist.find(params[:id])
  end
  def update
    artist = Artist.find(params[:id])
    artist.update_attributes(params[:artist])
    redirect_to(artist)
  end
  def destroy
    artist = Artist.find(params[:id])
    artist.delete
    redirect_to(artists_path)
  end
end

r2013-02-13-moma-rails/app/controllers/ paintings_controller.rb
class PaintingsController < ApplicationController
  def index
        @paintings = Painting.all
  end
  def create
  end
  def new
    @painting = Painting.new
  end
  def edit
  end
  def show
    @painting = Painting.find(params[:id])
  end
  def update
  end
  def destroy
    painting = Painting.find(params[:id])
    painting.delete
    redirect_to(paintings_path)
  end
end

r2013-02-13-moma-rails/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

r2013-02-13-moma-rails/app/helpers/application_helper.rb
module ApplicationHelper
end

r2013-02-13-moma-rails/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>R20130213MomaRails</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class="left">
  <nav>
  <ul>
    <li>ART.DB</li><br>
    <li><%= link_to('ARTISTS', artists_path) %></li>
    <br>
    <li><%= link_to('PAINTINGS', paintings_path) %></li><br>
     <li><%= link_to('ADD AN ARTIST', new_artist_path) %></li>
    <br>
    <li><%= link_to('ADD A PAINTING', new_painting_path) %></li>
  </ul>
</nav>
</div>
<div class="right">
<%= yield %>
</div>
</body>
</html>