Roland808/config/routes.rb
Roland808::Application.routes.draw do
  resources :samplers, :kits, :instruments
end

Roland808/app/models/instrument.rb
class Instrument < ActiveRecord::Base
  attr_accessible :name, :sound, :pic, :kit_id
  belongs_to :kits
end

Roland808/app/models/kit.rb
class Kit < ActiveRecord::Base
  attr_accessible :name, :pic, :sampler_id
  has_many :instruments
end

Roland808/app/models/sampler.rb
class Sampler < ActiveRecord::Base
  attr_accessible :name, :pic
  has_many :kits
end

Roland808/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

Roland808/app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController
  def index
    @instruments = Instrument.all
  end

  def create
    instrument = Instrument.create(params[:instrument])
    redirect_to(instruments_path)
  end

  def new
    @instrument = Instrument.new
  end

  def edit
    @instrument = Instrument.find(params[:id])
    render 'edit'
  end

  def show
    @instrument = Instrument.find(params[:id])
  end

  def update
    instrument = Instrument.find(params[:id])
    instrument.update_attributes(params[:instrument])
    redirect_to(instruments_path)
  end

  def destroy
    instrument = Instrument.find(params[:id])
    instrument.delete
    redirect_to(instruments_path)
  end
end

Roland808/app/controllers/kits_controller.rb
class KitsController < ApplicationController
  def index
    @kits = Kit.all
  end

  def create
    kit = Kit.create(params[:kit])
    redirect_to(kit)
  end

  def new
    @kit = Kit.new
  end

  def edit
    @kit = Kit.find(params[:id])
    render 'new'
  end

  def show
    @kit = Kit.find(params[:id])
  end

  def update
    kit = Kit.find(params[:id])
    kit.update_attributes(params[:kit])
    redirect_to(kits_path)
  end

  def destroy
    kit = Kit.find(params[:id])
    kit.delete
    redirect_to(kits_path)
  end
end

Roland808/app/controllers/samplers_controller.rb
class SamplersController < ApplicationController
  def index
    @samplers = Sampler.all
  end

  def create
    sampler = Sampler.create(params[:sampler])
    redirect_to(samplers_path)
  end

  def new
    @sampler = Sampler.new
  end

  def edit
    @sampler = Sampler.find(params[:id])
    render 'new'
  end

  def show
    @sampler = Sampler.find(params[:id])
  end

  def update
    sampler = Sampler.find(params[:id])
    sampler.update_attributes(params[:sampler])
    redirect_to(samplers_path)
  end

  def destroy
    sampler = Sampler.find(params[:id])
    sampler.delete
    redirect_to(samplers_path)
  end
end

Roland808/app/helpers/application_helper.rb
module ApplicationHelper
end

Roland808/app/views/kits/_form.html.erb
<%= form_for @kit do |f| %>
  <%= f.label :name, "Kit Name" %>
  <%= f.text_field :name %><br>
    <%= f.label :pic, "Image" %>
  <%= f.text_field :pic %>
  <br>
  <%= f.label :sampler_id %>
<%= f.select :sampler_id, Sampler.all.map{|sampler| [sampler.name, sampler.id]} %>
  <br>
  <%= f.submit %>
<% end %>

Roland808/app/views/kits/edit.html.erb
<%= render :partial => 'form' %>

Roland808/app/views/kits/index.html.erb
<% @kits.each do |kit| %>
      <%= link_to(kit.name, kit) %>
      <br>
      <%= image_tag(kit.pic) %><br>
<%= link_to 'Delete', kit, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_kit_path(kit) %>
<br>
<% end %>

Roland808/app/views/kits/new.html.erb
<%= render :partial => 'form' %>

Roland808/app/views/kits/show.html.erb
<%= @kit.name %>
<br>
<%= image_tag(@kit.pic) %>
<br>
<% @kit.instruments.each do |instrument| %>
<br>
  <%= link_to(instrument.name, instrument) %><br>
  <%= image_tag(instrument.pic) %><br>
<%= link_to 'delete', @instrument, :method => :delete, :confirm => 'Okay to delete?' %>
  <br>
<% end %>
<br>