r2013-02-14-cookbook/config/routes.rb
R20130214Cookbook::Application.routes.draw do
  resources :books, :recipes, :ingredients
end

r2013-02-14-cookbook/app/models/book.rb
# == Schema Information
#
# Table name: books
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  cuisine    :string(255)
#  chef       :string(255)
#  image      :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Book < ActiveRecord::Base
  attr_accessible :title, :cuisine, :chef, :image, :recipe_ids
  has_many :recipes
end

r2013-02-14-cookbook/app/models/ingredient.rb
# == Schema Information
#
# Table name: ingredients
#
#  id          :integer          not null, primary key
#  name        :string(255)
#  measurement :string(255)
#  cost        :decimal(, )
#  image       :text
#  recipe_id   :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#

class Ingredient < ActiveRecord::Base
  attr_accessible :name, :measurement, :cost, :image
  has_and_belongs_to_many :recipes
end

r2013-02-14-cookbook/app/models/recipe.rb
# == Schema Information
#
# Table name: recipes
#
#  id           :integer          not null, primary key
#  name         :string(255)
#  course       :string(255)
#  cooktime     :integer
#  servingsize  :integer
#  instructions :text
#  image        :text
#  book_id      :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

class Recipe < ActiveRecord::Base
  attr_accessible :name, :course, :cooktime, :servingsize, :instructions, :image, :book_id
  belongs_to :book
  has_and_belongs_to_many :ingredients
end

r2013-02-14-cookbook/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

r2013-02-14-cookbook/app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end
  def new
    @book = Book.new
  end
  def create
    book = Book.create(params[:book])
    redirect_to(book)
  end
  def show
    @book = Book.find(params[:id])
  end
  def edit
    @book = Book.find(params[:id])
    render 'new'
  end
  def update
    book = Book.find(params[:id])
    book.update_attributes(params[:book])
    redirect_to(book)
  end
  def destroy
    book = Book.find(params[:id])
    book.delete
    redirect_to(books_path)
  end
end

r2013-02-14-cookbook/app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def index
    @ingredients = Ingredient.all
  end
  def new
     @ingredient = Ingredient.new
  end
  def create
    ingredient = Ingredient.create(params[:ingredient])
    redirect_to(ingredient)
  end
  def show
     @ingredient = Ingredient.find(params[:id])
  end
  def edit
    @ingredient = Ingredient.find(params[:id])
    render 'new'
  end
  def update
    ingredient = Ingredient.find(params[:id])
    ingredient.update_attributes(params[:ingredient])
    redirect_to(ingredient)
  end
  def destroy
    ingredient = Ingredient.find(params[:id])
    ingredient.delete
    redirect_to(ingredients_path)
  end
end

r2013-02-14-cookbook/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = Recipe.all
  end
  def new
    @recipe = Recipe.new
  end
  def create
    recipe =  Recipe.create(params[:recipe])
    redirect_to(recipe)
  end
  def show
    @recipe = Recipe.find(params[:id])
  end
  def edit
    @recipe = Recipe.find(params[:id])
    render 'new'
  end
  def update
    recipe = Recipe.find(params[:id])
    recipe.update_attributes(params[:recipe])
    redirect_to(recipe)
  end
  def destroy
    recipe = Recipe.find(params[:id])
    recipe.delete
    redirect_to(recipe_path)
  end
end

r2013-02-14-cookbook/app/helpers/application_helper.rb
module ApplicationHelper
end

r2013-02-14-cookbook/app/views/recipes/_form.html.erb
<%= form_for @recipe do |f| %>
  <%= f.label :name, :autofocus => 'autofocus' %>
  <%= f.text_field :name %>
  <br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br>
  <%= f.label :course %>
  <%= f.text_field :course %>
  <br>
  <%= f.label :cooktime %>
  <%= f.text_field :cooktime %>
  <br>
  <%= f.label :servingsize %>
  <%= f.text_field :servingsize %>
  <br>
  <%= f.label :instructions %>
  <%= f.text_field :instructions %>
  <br>
  <%= f.submit %>
<% end %>

r2013-02-14-cookbook/app/views/recipes/edit.html.erb
<div class="right">
<br>
edit recipe!
<br>
<%= render :partial => 'form' %>
</div>

r2013-02-14-cookbook/app/views/recipes/index.html.erb
<% @recipes.each do |recipe| %>
<section>
<ol>
  <li>
    <ul>
      <li><%= image_tag(recipe.image) %></li>
      <li><%= link_to(recipe.name, recipe) %></li>
      <li><%= recipe.cooktime %></li>
      <li><%= recipe.course %></li>
      <li><%= recipe.servingsize %></li>
      <li><%= recipe.instructions %></li>
    </ul>
  </li>
</ol>
</section>
<% end %>

r2013-02-14-cookbook/app/views/recipes/new.html.erb
<div class="right">
<br>
new recipe!
<br>
<%= render :partial => 'form' %>
</div>

r2013-02-14-cookbook/app/views/recipes/show.html.erb
<div class='show'>
  <%= link_to @recipe.name, @recipe %>
  <%= @recipe.course %>
  <%= @recipe.cooktime %>
  <%= @recipe.servingsize %>
  <%= @recipe.instructions %>
  <%= image_tag(@recipe.image, :class =>'show') %>
</div>
<div class='links'>
<%= link_to 'Delete', @recipe, :method => :delete, :confirm => 'Okay to delete?' %>
<%= link_to 'Edit', edit_recipe_path(@recipe) %>
</div>